// The partner-job cities in Pakistan, India and Bangladesh: how many jobs
// each gets (by city size and where hiring happens) and well-known areas to
// place them in. geocode.mts looks every area up once and saves the result in
// places.json, so the jobs always land in the same, checked places.
export type City = {
  country: "PK" | "IN" | "BD";
  city: string;
  count: number;
  // Industrial cities get more factory jobs (see catalog.mts).
  industrial?: boolean;
  // The city centre, where the map search finds the district or division
  // instead of the city.
  center?: [number, number];
  areas: string[];
};

export const COUNTRY_NAMES = { PK: "Pakistan", IN: "India", BD: "Bangladesh" } as const;

export const CITIES: City[] = [
  // ------------------------------------------------------------ Pakistan: 1,000
  {
    country: "PK",
    city: "Karachi",
    count: 250,
    industrial: true,
    areas: [
      "Saddar",
      "Clifton",
      "DHA Phase 6",
      "Gulshan-e-Iqbal",
      "North Nazimabad",
      "PECHS",
      "Korangi Industrial Area",
      "SITE Area",
      "Gulistan-e-Jauhar",
      "Tariq Road",
      "Nazimabad",
      "Malir",
    ],
  },
  {
    country: "PK",
    city: "Lahore",
    count: 220,
    areas: [
      "Gulberg",
      "DHA Phase 5",
      "Johar Town",
      "Model Town",
      "Township",
      "Iqbal Town",
      "Anarkali",
      "Shadman",
      "Faisal Town",
      "Wapda Town",
      "Garden Town",
      "Cantt",
    ],
  },
  {
    country: "PK",
    city: "Faisalabad",
    count: 100,
    industrial: true,
    areas: [
      "D Ground",
      "Peoples Colony",
      "Madina Town",
      "Satiana Road",
      "Samanabad",
      "Jinnah Colony",
      "Ghulam Muhammad Abad",
    ],
  },
  {
    country: "PK",
    city: "Islamabad",
    count: 90,
    areas: ["Blue Area", "F-7", "F-10", "G-9", "I-8", "I-9", "E-11", "G-11"],
  },
  {
    country: "PK",
    city: "Rawalpindi",
    count: 90,
    areas: [
      "Saddar",
      "Satellite Town",
      "Commercial Market",
      "Chaklala",
      "Westridge",
      "Raja Bazaar",
    ],
  },
  {
    country: "PK",
    city: "Multan",
    count: 60,
    areas: ["Gulgasht Colony", "Bosan Road", "Cantt", "Shah Rukn-e-Alam Colony", "Hussain Agahi"],
  },
  {
    country: "PK",
    city: "Peshawar",
    count: 60,
    areas: ["University Town", "Hayatabad", "Saddar", "Gulbahar", "Warsak Road"],
  },
  {
    country: "PK",
    city: "Hyderabad",
    count: 40,
    areas: ["Latifabad", "Qasimabad", "Saddar", "Hirabad"],
  },
  {
    country: "PK",
    city: "Gujranwala",
    count: 40,
    industrial: true,
    areas: ["Satellite Town", "Model Town", "Peoples Colony", "Civil Lines"],
  },
  {
    country: "PK",
    city: "Sialkot",
    count: 30,
    industrial: true,
    areas: ["Cantt", "Paris Road", "Model Town", "Kashmir Road"],
  },
  {
    country: "PK",
    city: "Quetta",
    count: 20,
    areas: ["Jinnah Road", "Satellite Town", "Samungli Road", "Cantt"],
  },

  // ------------------------------------------------------------ India: 1,000
  {
    country: "IN",
    city: "Mumbai",
    count: 150,
    areas: [
      "Andheri East",
      "Andheri West",
      "Bandra West",
      "Lower Parel",
      "Powai",
      "Goregaon",
      "Malad",
      "Kurla",
      "Dadar",
      "Borivali",
      "Chembur",
      "Vikhroli",
    ],
  },
  {
    country: "IN",
    city: "Delhi",
    count: 150,
    areas: [
      "Connaught Place",
      "Karol Bagh",
      "Lajpat Nagar",
      "Rohini",
      "Dwarka",
      "Okhla",
      "Saket",
      "Janakpuri",
      "Nehru Place",
      "Laxmi Nagar",
      "Mayapuri",
      "Pitampura",
    ],
  },
  {
    country: "IN",
    city: "Bengaluru",
    count: 150,
    areas: [
      "Koramangala",
      "Whitefield",
      "Electronic City",
      "HSR Layout",
      "Indiranagar",
      "Marathahalli",
      "Jayanagar",
      "Yeshwanthpur",
      "Peenya",
      "BTM Layout",
      "Hebbal",
      "Rajajinagar",
    ],
  },
  {
    country: "IN",
    city: "Hyderabad",
    count: 100,
    areas: [
      "HITEC City",
      "Gachibowli",
      "Madhapur",
      "Kukatpally",
      "Secunderabad",
      "Banjara Hills",
      "Ameerpet",
      "Uppal",
      "Kondapur",
    ],
  },
  {
    country: "IN",
    city: "Chennai",
    count: 90,
    industrial: true,
    areas: [
      "T. Nagar",
      "Guindy",
      "Velachery",
      "Anna Nagar",
      "Adyar",
      "Sholinganallur",
      "Ambattur",
      "Tambaram",
    ],
  },
  {
    country: "IN",
    city: "Pune",
    count: 80,
    areas: [
      "Hinjawadi",
      "Kharadi",
      "Viman Nagar",
      "Kothrud",
      "Shivajinagar",
      "Hadapsar",
      "Wakad",
      "Baner",
    ],
  },
  {
    country: "IN",
    city: "Kolkata",
    count: 80,
    areas: [
      "Salt Lake",
      "Park Street",
      "New Town",
      "Gariahat",
      "Ballygunge",
      "Behala",
      "Dum Dum",
      "Esplanade",
    ],
  },
  {
    country: "IN",
    city: "Ahmedabad",
    count: 60,
    industrial: true,
    areas: ["Navrangpura", "Bodakdev", "Maninagar", "Satellite", "Naroda", "Vastrapur"],
  },
  {
    country: "IN",
    city: "Gurugram",
    count: 50,
    areas: ["Cyber City", "Sohna Road", "Udyog Vihar", "Golf Course Road", "Sector 29"],
  },
  {
    country: "IN",
    city: "Noida",
    count: 40,
    areas: ["Sector 18", "Sector 62", "Sector 63", "Sector 135"],
  },
  {
    country: "IN",
    city: "Jaipur",
    count: 30,
    areas: ["Malviya Nagar", "Vaishali Nagar", "C-Scheme", "Sitapura"],
  },
  {
    country: "IN",
    city: "Lucknow",
    count: 20,
    areas: ["Hazratganj", "Gomti Nagar", "Aliganj", "Alambagh"],
  },

  // ------------------------------------------------------------ Bangladesh: 500
  {
    country: "BD",
    city: "Dhaka",
    count: 250,
    industrial: true,
    areas: [
      "Gulshan",
      "Banani",
      "Dhanmondi",
      "Motijheel",
      "Uttara",
      "Mirpur",
      "Mohakhali",
      "Tejgaon",
      "Bashundhara",
      "Farmgate",
      "Mohammadpur",
      "Badda",
    ],
  },
  {
    country: "BD",
    city: "Chattogram",
    count: 90,
    industrial: true,
    areas: ["Agrabad", "GEC Circle", "Nasirabad", "Halishahar", "Panchlaish", "Patenga"],
  },
  {
    country: "BD",
    city: "Gazipur",
    count: 60,
    industrial: true,
    areas: ["Tongi", "Konabari", "Board Bazar", "Joydebpur", "Kashimpur"],
  },
  {
    country: "BD",
    city: "Narayanganj",
    count: 40,
    industrial: true,
    areas: ["Fatullah", "Siddhirganj", "Chashara", "Adamjee Nagar"],
  },
  {
    country: "BD",
    city: "Sylhet",
    count: 25,
    center: [24.8949, 91.8687],
    areas: ["Zindabazar", "Uposhohor", "Subid Bazar", "Tilagor"],
  },
  {
    country: "BD",
    city: "Khulna",
    count: 20,
    center: [22.8456, 89.5403],
    areas: ["Sonadanga", "Khalishpur", "Boyra", "Daulatpur"],
  },
  {
    country: "BD",
    city: "Rajshahi",
    count: 15,
    center: [24.3745, 88.6042],
    areas: ["Shaheb Bazar", "Kazla", "Laxmipur", "Uposhohor"],
  },
];
